[[tools]]
script = "codeql-nodocker.sh"
name = "CodeQL"
parse_command = { command = "bentoo", args = "convert codeql" }

[[tools.configs]]
name = "Go"
args = "--tech go"

[[tools]]
script = "semgrep.sh"
name = "Semgrep"
parse_command = { command = "bentoo", args = "convert semgrep" }

[[tools.configs]]
name = "Go"
args = ""

[[tools]]
script = "sonarqube.sh"
name = "SonarQube"
parse_command = { command = "bentoo", args = "convert sonarqube" }

[[tools.configs]]
name = "Go"
args = ""

[[tools]]
script = "bearer.sh"
name = "Bearer"
parse_command = { command = "bentoo", args = "convert bearer" }

[[tools.configs]]
name = "Go"
args = ""

[[tools]]
script = "snyk.sh"
name = "Snyk"
parse_command = { command = "bentoo", args = "convert snyk" }

[[tools.configs]]
name = "Go"
args = ""

[[tools]]
script = "gosec.sh"
name = "Gosec"
parse_command = { command = "bentoo", args = "convert gosec" }

[[tools.configs]]
name = "Go"
args = ""
