name: Build binaries

on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  x86-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the bentoo repository
        uses: actions/checkout@v4

      - name: Install x86_64-unknown-linux-musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build release (Linux)
        run: cargo build --target=x86_64-unknown-linux-musl --release -j`nproc`

      - name: Upload bentoo build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bentoo-x86-linux
          path: target/x86_64-unknown-linux-musl/release/bentoo
          retention-days: 1

  x86-macos:
    runs-on: macos-latest
    steps:
      - name: Clone the bentoo repository
        uses: actions/checkout@v4

      - name: Install x86_64-apple-darwin target
        run: rustup target add x86_64-apple-darwin

      - name: Build release (Mac OS x86)
        run: cargo build --target=x86_64-apple-darwin --release -j`sysctl -n hw.physicalcpu`

      - name: Upload bentoo build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bentoo-x86-macos
          path: target/x86_64-apple-darwin/release/bentoo
          retention-days: 1

  arm-macos:
    runs-on: macos-latest
    steps:
      - name: Clone the bentoo repository
        uses: actions/checkout@v4

      - name: Install x86_64-apple-darwin target
        run: rustup target add aarch64-apple-darwin

      - name: Build release (Mac OS ARM)
        run: cargo build --target=aarch64-apple-darwin --release -j`sysctl -n hw.physicalcpu`

      - name: Upload bentoo build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bentoo-arm-macos
          path: target/aarch64-apple-darwin/release/bentoo
          retention-days: 1


  tool_runners:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the bentoo repository
        uses: actions/checkout@v4

      - name: Upload bentoo build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tool_runners
          path: tool_runners
          retention-days: 1
