name: "Reference run"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  reference_run:

    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        # Using x86 Mac OS runner because M-series chips do not support nested virtualization
        runner: [ ubuntu-latest, macos-12 ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker on macOS
      if: runner.os == 'macos'
      run: |
        brew install docker
        colima start

    - name: Reference run (Mac OS)
      if: runner.os == 'macos'
      shell: bash
      run: ./playground/reference_run_macos.sh

    - name: Reference run
      if: runner.os != 'macos'
      shell: bash
      run: ./playground/reference_run.sh

    - name: Archive output
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.runner }}-output
        path: playground/play/output
