name: "Reference run"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  reference_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends \
          git \
          openjdk-11-jdk \
          openjdk-11-jre-headless \
          maven

    - name: Reference run
      shell: bash
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
        ./playground/reference_run.sh

    - name: Archive output
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output
        path: playground/play/output
