name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build_binaries.yml

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          prerelease: true
          generate_release_notes: true
          files: |
            LICENSE
            target/x86_64-unknown-linux-musl/release/bentoo.tar.gz
            target/x86_64-apple-darwin/release/bentoo.tar.gz
            target/aarch64-apple-darwin/release/bentoo.tar.gz
            tool_runners.tar.gz
