name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build_binaries.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone the bentoo repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/artifacts

      - name: debug
        run: ls ${{ github.workspace }}/artifacts/bentoo-x86-linux

      - name: Compress release files
        working-directory: ${{ github.workspace }}/artifacts
        run: |
          chmod +x bentoo-x86-linux/bentoo
          chmod +x bentoo-x86-macos/bentoo
          chmod +x bentoo-arm-macos/bentoo
          chmod +x tool_runners/*.sh
          tar -czvf bentoo-x86-linux.tar.gz -C bentoo-x86-linux bentoo
          tar -czvf bentoo-x86-macos.tar.gz -C bentoo-x86-macos bentoo
          tar -czvf bentoo-arm-macos.tar.gz -C bentoo-arm-macos bentoo
          tar -czvf tool_runners.tar.gz tool_runners

      - name: Publish Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          prerelease: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            LICENSE
            ${{ github.workspace }}/artifacts/*
