name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the bentoo repository
        uses: actions/checkout@v4

      - name: Install x86_64-unknown-linux-musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build release
        run: cargo build --target=x86_64-unknown-linux-musl --release -j`nproc`

      - name: Upload bentoo build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bentoo-linux
          path: target/x86_64-unknown-linux-musl/release/bentoo
          retention-days: 1

      - name: Compress binary
        working-directory: target/x86_64-unknown-linux-musl/release
        run: tar -czvf bentoo.tar.gz bentoo

      - name: Compress tool runers
        run: tar -czvf tool_runners.tar.gz tool_runners

      - name: Publish Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          prerelease: true
          generate_release_notes: true
          files: |
            LICENSE
            target/x86_64-unknown-linux-musl/release/bentoo.tar.gz
            tool_runners.tar.gz
